import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 16,
    backgroundColor: "#FFFFFF",
    fontFamily: "Roboto-Regular",
    justifyContent: "space-between",
  },
  imageBox: {
    width: "100%",
    height: 240,
    marginTop: 32,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    borderRadius: 8,
    backgroundColor: "#F6F6F6",
  },
  image: {
    flex: 1,
    width: "100%",
    borderRadius: 8,
    resizeMode: "cover",
  },
  list: {
    width: "100%",
    marginVertical: 20,
  },
  item: {
    width: "100%",
    marginVertical: 12,
    gap: 16,
  },
  avatar: {
    width: 28,
    height: 28,
    resizeMode: "cover",
    borderRadius: 50,
    backgroundColor: "#F6F6F6",
  },
  avatarBox: {
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  guestComment: {
    flex: 1,
    padding: 16,
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    borderTopRightRadius: 6,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  ownerComment: {
    flex: 1,
    padding: 16,
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    borderTopLeftRadius: 6,
  },
  coment: {
    fontSize: 13,
    lineHeight: 18,
    color: "#212121",
    textAlign: "left",
  },
  data: {
    color: "#BDBDBD",
    marginTop: 8,
    fontSize: 10,
    lineHeight: 12,
  },
  inputBox: {
    position: "relative",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  input: {
    width: "100%",
    height: 59,
    borderWidth: 1,
    borderColor: "#E8E8E8",
    backgroundColor: "#F6F6F6",
    paddingVertical: 16,
    paddingLeft: 16,
    paddingRight: 50,
    borderRadius: 100,
    color: "#212121",
    fontSize: 16,
  },
  btnSend: {
    position: "absolute",
    width: 34,
    height: 34,
    right: 8,
    backgroundColor: "#FF6C00",
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
});

export default styles;